amf-ipv4-address: 169.169.20.175
band: 41
plmn-id: 26203

#ssb-subcarrier-offset :
#absolute-frequency-ssb:
#absolute-frequency-point-a :
#ssb-frequency:
#ref-frequency-csi-rs:
#pdcch-config-sib1:
#pusch_addtiona: