services:amf-ipv4-address: 169.169.20.110
services:band: 79
services:plmn-id: 26203
services:extend-tracking-area-code: 4386

#services:ssb-subcarrier-offset :
#services:absolute-frequency-ssb:
#services:absolute-frequency-point-a :
#services:ssb-frequency:
#services:pdcch-config-sib1:.