services:amf-ipv4-address: 169.169.20.177
services:band: 41
services:plmn-id: 46099
services:extend-tracking-area-code: 4386

#services:ssb-subcarrier-offset :
#services:absolute-frequency-ssb:
#services:absolute-frequency-point-a :
#services:ssb-frequency:
#services:pdcch-config-sib1:.