amf-ipv4-address: 169.169.20.175
band: 79
reference_frequency: 256500
plmn-id: 26203


amf-ipv4-address
ssb-subcarrier-offset
absolute-frequency-ssb
absolute-frequency-point-a
plmn-id
band
ssb-frequency
ref-frequency-csi-rs
pdcch-config-sib1
pusch_addtiona