5GC_Type:
  Type: 中电
  IP: 10.88.120.200
  Config_tex: None
BBU_Type:
  Type: 中电
  IP: 10.88.120.160
  Config_tex: None
HUB_Type:
  Type: O-RAN
  IP: 192.168.255.11
  Config_tex: None
RRU_Type:
  Type: O-RAN
  IP: 192.168.255.1
  Config_tex: None

